version: "3"

services:
  parley-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlite:db.sqlite"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.sqlite.JDBC"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.SQLiteDialect"
    deploy:
      resources:
        limits:
          memory: 450m
