spring:
  application:
    name: parley-bot
  messages:
    basename: i18n/messages
  data:
    mongodb:
      database: parley
      uri: ${MONGO_URI}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

bot:
  token: ${BOT_TOKEN}

google:
  project-id: ${GOOGLE_PROJECT_ID}
  location: ${GOOGLE_PROJECT_LOCATION}

