spring:
  application:
    name: parley-bot
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:sqlite:/data/db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

bot:
  token: ${BOT_TOKEN}

open-ai:
  host: https://api.openai.com
  api-key: ${OPENAI_API_KEY}

